pass_manager/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignUpView, pass_manager_view, pass_manager_share_view


urlpatterns = [
    path('', LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('pass-manager/', pass_manager_view, name='pass-manager'),
    path('pass-manager-share/', pass_manager_share_view, name='pass-manager-share')
]

pass_manager/api/urls.py
from django.urls import path
from .views import PassSiteApiView, PassSiteDetailApiView, CreatePassSiteShareApiView

urlpatterns = [
    path('pass-site/', PassSiteApiView.as_view(), name='pass-site'),
    path('pass-site-detail/', PassSiteDetailApiView.as_view(), name='pass-site-detail'),
    path('create-pass-site-share/', CreatePassSiteShareApiView.as_view(), name= 'create-pass-site-share')

]

pass_manager/pass_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('api/', include(('api.urls', 'api'), namespace='api'))
]

pass_manager/accounts/models.py
from django.db import models

# Create your models here.

pass_manager/api/models.py
from django.db import models
from django.contrib.auth.models import User

class PassSite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    site_name = models.CharField('Name of a site', max_length=120)
    site_url = models.CharField('Site\'s url', max_length=120)
    account_name = models.CharField('Name of your account',max_length=120)
    account_password = models.CharField('Password to your account', max_length=172)

    def __str__(self):
        return "{}, site_name: {}, site_url: {}, account_name: {}, account_password: {}".format(self.user, self.site_name, self.site_url, self.account_name, self.account_password)

pass_manager/accounts/views.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.shortcuts import render
from django.views import View
import jwt
from django.contrib.messages import constants as messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings


class SignUpView(SuccessMessageMixin, FormView):
    template_name = 'signup.html'
    form_class = UserCreationForm
    success_url = '/'
    success_message = 'Account created successfully'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

@login_required(login_url=settings.LOGOUT_REDIRECT_URL)
def pass_manager_view(request):
    return render(request, 'pass-manager.html')

def pass_manager_share_view(request):
    try:
        token = request.GET.get('token', '')
        encoded_token = jwt.decode(token, 'secret', algorithms=['HS256'])
        return render(request, 'pass-manager-share.html', context=encoded_token)
    except jwt.exceptions.ExpiredSignatureError:
        return render(request, 'pass-manager-share.html')

pass_manager/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse, HttpResponseForbidden
from django.contrib.auth.models import User
from .models import PassSite
from .serializer import PassSiteSerializer
from rest_framework import status
from django.shortcuts import get_object_or_404
import jwt
from datetime import datetime, timedelta
from .hash_password import hash, unhash
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated


class PassSiteApiView(APIView):
    serializer_class = PassSiteSerializer

    authentication_classes = (SessionAuthentication, )
    permission_classes = (IsAuthenticated,)



    def get(self, request, format=None):
        data = PassSite.objects.filter(user__id=request.GET['id'])
        for d in data:
            d.account_password = unhash(d.account_password)
        serializer = self.serializer_class(data, many=True)
        return JsonResponse(serializer.data, safe=False)

    def post(self, request, format=None):
        request.data['account_password'] = hash(request.data['account_password'])
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class PassSiteDetailApiView(APIView):
    serializer_class = PassSiteSerializer

    authentication_classes = (SessionAuthentication, )
    permission_classes = (IsAuthenticated,)

    def get_object(self, pk, user):
        return get_object_or_404(PassSite, user=user, pk=pk)

    def get(self, request, format=None):
        pass_site = self.get_object(request.data['id'], request.user)
        serializer = self.serializer_class(pass_site)
        return Response(serializer.data)
    
    def put(self, request, format=None):
        pass_site = self.get_object(request.data['id'], request.user)
        request.data['account_password'] = hash(request.data['account_password'])
        serializer = self.serializer_class(pass_site, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, format=None):
        pass_site = self.get_object(request.GET.get('pk',''), request.user)
        pass_site.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CreatePassSiteShareApiView(APIView):

    def post(self, request, format=None):
        request.data['exp'] = datetime.utcnow()+ timedelta(minutes=5)
        jwt_payload = str(jwt.encode(request.data, 'secret', algorithm='HS256'))[2:-1]
        return JsonResponse({'token': jwt_payload}, status=status.HTTP_201_CREATED)

pass_manager/accounts/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
</table>

<input class='btn btn-primary' type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>
<p>Don't have account yet?</p>
<a class='btn btn-primary' href= "{% url 'accounts:signup' %}">Sign up</a>
{# Assumes you setup the password_reset view in your URLconf #}

{% endblock %}

pass_manager/accounts/templates/pass-manager-share.html
{% extends "base.html" %}

{% block content %}
    {% if site_name %}
        <div class='row'>
            <div class='col-3'>
            </div>
            <div class='col-6'>
                <h1> SHARED DATA </h1>
                <table class='table table-bordered table-dark table-hover'>
                    <thead>
                        <tr>
                            <th scope='row'> Site name</th>
                            <th> {{site_name}}</th>
                        </tr>
                        <tr>
                            <th scope='row'> Site url </th>
                            <th> {{site_url}}</th>
                        </tr>
                        <tr>
                            <th scope='row'> Account name</th> 
                            <th> {{account_name}}</th>
                        </tr>
                        <tr>
                            <th scope='row'> Account password</th> 
                            <th> {{account_password}}</th>
                        </tr>
                    </thead>
                </table>        
            </div>
            <div class='col-3'>
                    
            </div>
        </div>
    {% else %}
        <h1>I guess that your token is not valid anymore :(</h1>
    {% endif %}

{% endblock %}

pass_manager/accounts/templates/pass-manager.html
{% extends "base.html" %}

{% block content %}
<div id='app'></div>
<script type='text/babel'>

    class App extends React.Component {
        customStyles = {
            content : {
                top: '50%',
                left: '50%',
                right: 'auto',
                bottom: 'auto',
                marginRight: '-50%',
                transform: 'translate(-50%, -50%)'
            }
        };
        constructor(props){
            super(props)
            this.state = {
                passes: [],
                modalIsOpen: false,
                pass_id: '',
                siteName: '',
                siteUrl: '',
                accountName: '',
                accountPassword: '',
                sharedLink: '',
                addingMode: false,
                deletingMode: false,
            }

            axios.defaults.xsrfCookieName = 'csrftoken'
            axios.defaults.xsrfHeaderName = 'X-CSRFToken'

            axios.get("{% url 'api:pass-site' %}", {
                params: {
                    id: {{request.user.id}}
                }
            })
            .then(res => {
                this.setState({ passes: res.data });
            })
        }

        CSRFToken = () => {
            var csrftoken = this.getCookie('csrftoken');
            return (
                <input type="hidden" name="csrfmiddlewaretoken" value={csrftoken} />
            );
        };

        componentWillMount() {
            ReactModal.setAppElement('body');
        }

        getCookie = (name) => {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                let cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    let cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        openModal = (pass) => {
            if (pass == 'add') {
                this.setState({
                    addingMode: true,
                    modalIsOpen: true,
                    deletingMode: false,
                });
            }
            else {
                this.setState({
                    modalIsOpen: true,
                    addingMode: false,
                    pass_id: pass.id,
                    siteName: pass.site_name,
                    siteUrl: pass.site_url,
                    accountName: pass.account_name,
                    accountPassword: pass.account_password,
                });
            }
        }

        closeModal = () => {
            this.setState({
                modalIsOpen: false,
                pass_id: '',
                siteName: '',
                siteUrl: '',
                accountName: '',
                accountPassword: '',
                sharedLink: '',
                deletingMode: false,
            });
        }
        
        siteNameHandler = (e) => { this.setState({siteName: e.target.value}) }

        siteUrlHandler = (e) => { this.setState({siteUrl: e.target.value}) }

        accountNameHandler = (e) => { this.setState({accountName: e.target.value}) }

        accountPasswordHandler = (e) => { this.setState({accountPassword: e.target.value}) }

        deletingModeHandler = () => { this.setState({deletingMode: true}) }

        shareFunction = (e) => {
            const body = {
                    user: {{request.user.id}},
                    site_name: this.state.siteName,
                    site_url: this.state.siteUrl,
                    account_name: this.state.accountName,
                    account_password: this.state.accountPassword,
                };
            let csrftoken = this.getCookie('csrftoken');
            axios.post("{% url 'api:create-pass-site-share'%}", body, {headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                }}).then((res) => {
                    let hostname = window.location.hostname + ":" + window.location.port
                    this.setState({
                        sharedLink: hostname + "/pass-manager-share/?token=" + res.data.token
                    })
                });
        }

        sendPassSiteFunction = (e) => {
            const body = {
                    user: {{request.user.id}},
                    site_name: this.state.siteName,
                    site_url: this.state.siteUrl,
                    account_name: this.state.accountName,
                    account_password: this.state.accountPassword,
                }
            let csrftoken = this.getCookie('csrftoken');
            if (this.state.addingMode == true){
                axios.post("{% url 'api:pass-site' %}", body, {headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                }})
            }
            else if (this.state.deletingMode == true){
                body.id = this.state.pass_id
                axios.delete("{% url 'api:pass-site-detail' %}"+ "?pk="+ this.state.pass_id, {headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                }})
            }
            else{
                body.id = this.state.pass_id
                axios.put("{% url 'api:pass-site-detail' %}", body, {headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                }})
            }
         
        }


        modalShareComponentsFunction = () => {
            if(this.state.addingMode == false){
                return (
                    <div>
                        <p><button className='btn btn-primary' onClick={this.shareFunction}>SHARE!</button></p>
                        <input onFocus={e => e.target.select()} type='text' value={this.state.sharedLink} />
                    </div>
                )
            }
        }

        modalPasswordInput = () => {
            if (this.state.addingMode == true){
                return (
                    <div>
                        <p><input onChange={this.accountPasswordHandler} type='text' placeholder='account password' value={this.state.accountPassword}/></p>
                        <button className='btn btn-primary'>add</button>                                        
                    </div>
                )
            }
            else{
                return (
                    <div>
                        <p><input disabled onChange={this.accountPasswordHandler} type='text' placeholder='account password' value={this.state.accountPassword}/></p>
                        <button className='btn btn-primary'>change</button>
                        <button onClick={this.deletingModeHandler} className='btn btn-danger'>delete</button>     
                    </div>
                )
            }
        }
        render() {
            return (
                <div className='app-component'>
                    <button onClick={() => this.openModal('add')} className='btn btn-primary'>Add Pass</button>
                    <p></p>
                    <table className='table table-bordered table-dark table-hover'>
                        <thead>
                            <tr>
                                <th scope='col'>#</th>
                                <th scope='col'> Site name </th>
                                <th scope='col'> Site url link </th>
                                <th scope='col'> Details </th> 
                            </tr>
                        </thead>
                        <tbody>
                            {this.state.passes.map((pass, index) => {
                                let href_value = "http://" + pass.site_url
                                return (
                                    <tr key={pass.id} onClick={this.passHandler}>
                                        <th scope='row'>{index}</th>
                                        <td>{pass.site_name}</td>
                                        <td><a href={href_value} target="_blank">{pass.site_url}</a></td>
                                        <td><button onClick={() => this.openModal(pass)} className='btn btn-primary'>Details</button></td>
                                    </tr>
                                )
                            })}
                        </tbody>
                    </table>
                    <ReactModal
                        isOpen={this.state.modalIsOpen}
                        onRequestClose={this.closeModal}
                        style={this.customStyles}
                    >
                        <form onSubmit={this.sendPassSiteFunction}>
                            {this.CSRFToken()}
                            <p><input onChange={this.siteNameHandler} type='text' placeholder='site name' value={this.state.siteName}/></p>    
                            <p><input onChange={this.siteUrlHandler} type='text' placeholder='site url' value={this.state.siteUrl}/></p> 
                            <p><input onChange={this.accountNameHandler} type='text' placeholder='login account name' value={this.state.accountName}/></p>    
                            { this.modalPasswordInput() }
                        </form>
                        {this.modalShareComponentsFunction()}
                        <p><button className='btn btn-close' onClick={this.closeModal}>close</button></p>

                    </ReactModal>
                </div>
            )
        }
    }
    ReactDOM.render(<App />, document.getElementById('app'))
</script>
{% endblock %}

pass_manager/accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

pass_manager/app/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'app:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}

{% endblock %}

pass_manager/pass_manager/templates/base.html
{% load static %}

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.17.0/babel.min.js"></script>
  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.6.1/react-modal.js"></script>
</head>

<body>
  {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
  {% endfor %}
  <div class='row'>
    <div class='col-2'>

    </div>
    <div class='col-8'>
      <br>
      {% block content %}
      {% endblock %}
    </div>
    <div class='col-2'>
        <br>
      <a class='btn btn-primary' href='{% url "accounts:logout" %}'>LOGOUT</a>
    </div>
  </div>

</body>